name: pylint then build

on:

  push:
    branches:
      - main
      - development
  pull_request:
    types:
      - closed  # Trigger when the pull request is closed
    branches:
      - main
      - development
jobs:
  lint:
    name: Lint Code with Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip freeze > requirements.txt

    - name: Run Pylint
      env:
        PYTHONPATH: src/
      run: |
        pylint src/

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint # Ensure linting passes before building the Docker image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t your-image-name:latest .
  auto-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true  # Only run if the pull request was merged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Auto-merge pull request
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_MERGE }}
      run: |
        # Merge the pull request
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_TOKEN")
        curl \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H 0
          -author" Release...
