name: pylint then build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  lint:
    name: Lint Code with Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip freeze > requirements.txt

    - name: Run Pylint
      env:
        PYTHONPATH: tempreportgenerator/
      run: |
        pylint src/

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting passes before building the Docker image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t your-image-name:latest .
